modLoader="javafml"
loaderVersion="[35,)"
license="MIT License, Copyright 2021 MRH0"

[[mods]]
modId="creategearaddon"
version="${file.jarVersion}"
displayName="Create gear addon"
authors="xaros74"
description='''
This is a simple mod that add gears with textures colors from vanilla wood.
'''

[[dependencies.creategearaddon]] #optional
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.creategearaddon]]
    modId="create"
    mandatory=true
    versionRange="[mc1.16.5_v0.3.2d,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.creategearaddon]]
    modId="creategears"
    mandatory=false
    versionRange="[mc1.16.5-1.3.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.creategearaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
