modLoader="javafml"
loaderVersion="[37,)"
license="MIT License, Copyright 2021 MRH0"

[[mods]]
modId="creategearaddon"
version="${file.jarVersion}"
displayName="Create gear addon"
#logoFile="creategearaddon.png"
authors="xaros74"
description='''
This is a simple mod that add gears with different color textures.
'''

[[dependencies.creategearaddon]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creategearaddon]]
    modId="create"
    mandatory=true
    versionRange="[mc1.17.1_v0.4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.creategearaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
